"use strict";

module.exports = {
  apps: [
    {
      name: "aeonops",
      cwd: "/home/aeon-rag",
      script: "pnpm",
      args: "start",
      autorestart: true,
      min_uptime: "20s",
      max_restarts: 50,
      restart_delay: 5000,
      exp_backoff_restart_delay: 100,
      kill_timeout: 10000,
      max_memory_restart: "800M",
      env: {
        NODE_ENV: "production",
        PORT: "3000",
      },
    },
    {
      name: "aeonops-watchdog",
      cwd: "/home/aeon-rag",
      script: "bash",
      args: "scripts/self-heal-loop.sh",
      autorestart: true,
      min_uptime: "5s",
      max_restarts: 50,
      restart_delay: 2000,
      exp_backoff_restart_delay: 100,
      kill_timeout: 5000,
      env: {
        NODE_ENV: "production",
        AEON_HEALTH_URL: "http://127.0.0.1:3000/api/health",
        SELF_HEAL_INTERVAL_SECONDS: "30",
      },
    },
    {
      name: "aeonops-drive-worker",
      cwd: "/home/aeon-rag",
      script: "pnpm",
      args: "run rag:drive:worker",
      autorestart: false,
      min_uptime: "5s",
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 15000,
      env: {
        NODE_ENV: "production",
        DRIVE_WORKER_ENABLED: "true",
        DRIVE_WORKER_FOLDER: "AEON_Master_Intake",
        DRIVE_WORKER_FOLDER_ID: "1UxcB_zept-UQVgPcN9DHPwkur6jAN6B4",
        DRIVE_WORKER_LIMIT: "200",
        DRIVE_WORKER_INTERVAL_SECONDS: "300",
        DRIVE_WORKER_EXT: ".txt,.md,.json,.ts,.tsx,.py,.js,.pdf",
      },
    },
  ],
};
